tache_index:
    path:     /
    defaults: { _controller: "grhBundle:tache:index" }
    methods:  GET

tache_show:
    path:     /{id}/show
    defaults: { _controller: "grhBundle:tache:show" }
    methods:  GET

tache_new:
    path:     /new
    defaults: { _controller: "grhBundle:tache:new" }
    methods:  [GET, POST]

tache_edit:
    path:     /{id}/edit
    defaults: { _controller: "grhBundle:tache:edit" }
    methods:  [GET, POST]

tache_delete:
    path:     /{id}/delete
    defaults: { _controller: "grhBundle:tache:delete" }
    methods:  DELETE
