<?php

namespace grh\Bundle\Repository;

/**
 * tacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tacheRepository extends \Doctrine\ORM\EntityRepository
{
}
